# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(default='', help_text='The episode title', verbose_name='title')),
                ('duration', models.TextField(blank=True, default='', help_text='Duration of enclosure', verbose_name='duration')),
                ('published_date', models.DateTimeField(help_text='Date item was published', verbose_name='published_date')),
                ('image', models.URLField(blank=True, default='', help_text='URL of item cover art', max_length=1024, verbose_name='image')),
                ('enclosure_url', models.URLField(blank=True, default='', help_text='The URL of item.', max_length=1024, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.FloatField(help_text='How much the user has listened', verbose_name='duration')),
                ('finished', models.BooleanField(help_text='True when the user has finished listening to this episode', verbose_name='finished')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(default='', help_text='The podcast title', verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscribed', models.BooleanField(default=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listeningprogress',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Subscription'),
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcast'),
        ),
    ]
