# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', help_text='The episode title', verbose_name='title')),
                ('podcastTitle', models.TextField(default='', help_text='The podcast title', verbose_name='title')),
                ('publishedDate', models.DateTimeField(help_text='Date item was published', verbose_name='published_date')),
                ('image', models.URLField(blank=True, default='', help_text='URL of item cover art', max_length=1024, verbose_name='image')),
                ('url', models.URLField(blank=True, default='', help_text='The URL of item.', max_length=1024, verbose_name='url')),
                ('duration', models.FloatField(help_text='Total Lenght of the audio file', verbose_name='duration')),
                ('currentTime', models.FloatField(default=0, help_text='How much the user has listened', verbose_name='currentTime')),
            ],
        ),
    ]
