# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningprogress',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='listeningprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='episode',
            name='listening_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcast.ListeningProgress'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.TextField(blank=True, default='', help_text='Duration of enclosure', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.URLField(blank=True, default='', help_text='URL of item cover art', max_length=1024, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.TextField(default='', help_text='The episode title', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.TextField(default='', help_text='The podcast title', verbose_name='title'),
        ),
    ]
