# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcast', '0002_auto_20170908_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='listening_progress',
        ),
        migrations.AddField(
            model_name='listeningprogress',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='podcast.Episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listeningprogress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
